encoding: utf-8

# SEO相关信息
title: Chuanyu Blog
description: Chuanyu's Personal blog
keywords: Chuanyu, Blog, Datamining, Python
author: Chuanyu
footerText: 'Copyright © Chuanyu Xue'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', 'build']

# 域名配置
# baseUrl配置,如果网站部署在根目录下的目录中，请设置为 /目录名
domainUrl: 'https://chuanyu2019.club'
baseUrl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://www.zhihu.com/people/xuechuanyu/activities

# 菜单
menu:
  - title: Biography
    url: /
  - title: Blog
    url: /pages/chat.html
  - title: Links
    url: /pages/links.html
  - title: Download my CV
    url: /pages/about.html

# 自定义插件
# plugin-mta-stats
# 腾讯移动分析(https://mta.qq.com)，如果需要请申请自己的，不需要的话 use 请设置为 false
# plugin-baidu-push
# 百度收录自动推送，不需要的话 use 请设置为 false
# plugin-click-effect
# 页面点击，出现核心主义价值观
# plugin-mathjax
# 数学公式支持，比较影响加载速度，请设置为 false
customPlugins:
  - use: false
    file: 'plugin-mta-stats.html'
    sid: 500581966
    cid: 500581972
  - use: true
    file: 'plugin-baidu-push.html'
  - use: false
    file: 'plugin-click-effect.html'
  - use: false
    file: 'plugin-mathjax.html'

# 友情链接
links:
  - title: Chuanyu 的音乐空间
    url: https://music.163.com/#/user/home?id=40811754
  - title: Chuanyu 的社交账号
    url: https://zhihu.com/people/xuechuanyu
  - title: Chuanyu 的Linkin
    url: https://linkedin.com/in/chuanyuxue 
  - title: Chuanyu 的Github
    url: https://github.com/ChuanyuXue 

